== *文字コードについて*

=== 文字コードとは
文字コードは文字セット（符号化文字集合）と符号化方式の２つの意味を合わせて使用されている。
文字セットとは、言語や記号体系に関連付けられた一連の文字や記号の集合を表している。 +
ex)Unicode +
符号化方式とは、文字セットで規定された文字をコンピュータでバイト列に変換するための方式である。 +
ex)Unicodeの場合、UTF-8やUTF-16が使用される。 +

=== 文字化けについて
文字化けが発生する要因は様々で、APやOSの設定により異なる。 +
以下に例を示す。 +

. フォントの不一致 +
表示しようとしている文字が、利用しているフォントに含まれていない場合、その文字は適切に表示されない。 +
例えば、Unicodeにない特定の文字が含まれているフォントを使用すると、文字化けが発生する可能性があります。 +
そのため、例えばUnicodeを使用し、UTF-8でエンコーディングしている場合は、Unicodeに対応してフォントを使用する必要がある。 +
CSSのfontfamilyでフォントを指定する際は、使用している文字セットに対応したフォントを使用することが重要。

. 符号化方式の不一致 +
テキストデータが特定の符号化方式（エンコーディング）でエンコードされ、表示に使用されるフォントの期待される符号化方式と一致しない場合、文字が誤って解釈されることがある。 +
例えば、UTF-8でエンコードされたテキストをISO-8859-1のフォントで表示しようとすると、文字化けが発生する。 +

. フォントの欠落 +
表示に必要なフォントがシステムにインストールされていない場合、代替のフォントが使用され、文字化けが発生する可能性がある。

. OSやアプリケーションの設定 +
オペレーティングシステムやアプリケーションの設定が、文字コードの正しい解釈に関わる重要な要因である。設定が正しくない場合、文字化けが発生することがある。 +

=== DBへの登録の際の考え方
例えば、自由入力欄があり、入力された文字列をDBのカラム（String）に登録する場合は考える。 +
この場合、DBやAP側で円弧―ディングの方法が設定されており、指定された方法でエンコーディングされたバイト列が登録されることになる。


